# Generated by Django 5.2 on 2025-05-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(max_length=100, verbose_name="User Name"),
                ),
                ("password", models.CharField(max_length=100, verbose_name="Password")),
                ("email", models.CharField(max_length=100, verbose_name="Email")),
            ],
            options={
                "verbose_name": "Custom User",
                "verbose_name_plural": "Custom Users",
                "db_table": "custom_user",
            },
        ),
    ]
