# Generated by Django 5.2 on 2025-05-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="User Name"
            ),
        ),
    ]
