# Generated by Django 5.2 on 2025-05-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_testresult_custom_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="test_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Test Time"),
        ),
    ]
